### ISSUE TITLE
Unimplemented instruction

### ISSUE THREAD

**Issue by lurk101** [jdykstra/ucsd-psystem-vm#2] opened 2021-11-11 02:54 UTC
I'm porting this to the Raspberry Pico and was getting an error, so I built this repo under Ubuntu 21.10 on an X86 box and ran it.

This

_program home;
  var a : real;
begin
  writeln('Hello');
  a := 0;
  writeln(a);
end._

Compiles without error but when run gets

_Running
Hello

Unimplemented instruction
S# 1, P# 1, I# 4826
Type <space> to continue_

I've debugged it down to [this](https://github.com/jdykstra/ucsd-psystem-vm/blob/43c8fb9fc86dfba3a4ae78ec1256630fa533b388/ucsdpsys_vm/native6502.c#L619) statement. But I've no idea what all of these signature strings are? 

Any operation on REAL variables will cause this runtime error.

**Comment by ghaerr** [comment] 2021-11-11 04:19
Hello @lurk101,

Sorting through all this seems pretty complicated, but nice job finding out where the problem occurred. That allowed me to figure out what I think is going on:

It seems that this (Peter Miller's version of the UC Pascal VM) is based off a lot of work put in by Mario Klebsch back in 2000 or so, to write an interpreter in C that would run the binary Apple II Pascal System Disks. Although lots of source was made public for the UC p-system, not everything was available, it seems. Mario's interpreter source is at http://klebsch.de, and though written in German, his last version is available there as p-interp v0.5, and can be downloaded.

Looking through that seems to show that the UC Pascal system had various "UNITS", that is external callable procedures grouped onto disk, for various parts of the UCSD distribution, such as SYSTEM.LIBRARY, where various native functions, like LONGINT are implemented, and also the APPLESTUFF UNIT, where it seems REALs are implemented.

The compiler generates code to call these native procedures, which are written in assembly language. The source for those seems to be not available, but Mario figured some out and reimplemented them in C, namely LONGINTs. I think what is going on is the ProcessNative function where the interpreter is stopping tries to identify these native procedures based on 6502 binary code signatures, rather than by native procedure number. Why that is, I'm not sure.

Mario mentions in the 'ucsd.1' man page that lots of native functions from the Apple Pascal System (UNIT APPLESTUFF) are still missing, and it seems that REAL (i.e. floating point) is not implemented. That may be because they were trying to achieve binary compatibility with the original Apple disks, to run any programs for which source is not available, and few binary programs in the distribution required REALs.

The [attached](https://github.com/jdykstra/ucsd-psystem-vm/files/7517708/Internal_Architecture-1.140.41.A.pdf) page describes DECOPS (decimal operations) which is from the LONGOPS unit, taken from the Softech Microsystems p-system Software Reference Manual, available on the net. This gives a bit more information about this.

I hope this helps; it will probably be a lot of work to get REAL variables functional, it would seem!

Thank you!

**Comment by jdykstra** [comment] 2021-11-11 17:14
Thanks for the problem report, @lurk101!  Are your compiling your testcase using the P-System compiler, either on your Rasberry Pi or under the VM on Linux, or are you using Peter Miller's cross-compiler?

This may be a P-System version issue.  The II.0 interpreters written at UCSD implemented basic floating point ops directly, called by specific p-opcodes.  The floating point support was a conditional assembly option, because it used a fair amount of space, but if your interpreter was built with it, you didn't need any native code UNITs.

Peter Miller's VM implements these floating point p-opcodes, probably inherited from Mario Klebsch's work, as noted by @ghaerr .  So your problem may be that the compiler isn't emitting these opcodes.

**Comment by jdykstra** [comment] 2021-11-11 22:16
Here's the code for your testcase generated by the II.0.A.1 compiler included in Peter Miller's system disk image:

; Procedure 1:
0000: D5 04             p1_0:   BPT     4
0002: B6 01 03                  LOD     1, 3
0005: A6 05 48 65 6C            LSA     5, "Hello"
      6C 6F
000C: D7                        NOP
000D: 00                        SLDC    0
000E: CD 00 13                  CXP     0, 19           ; fwritestring
0011: 9E 00                     CSP     IOCHECK
0013: B6 01 03                  LOD     1, 3
0016: CD 00 16                  CXP     0, 22           ; fwriteln
0019: 9E 00                     CSP     IOCHECK
001B: A5 03                     LAO     3
001D: 00                        SLDC    0
001E: 8A                        FLT
001F: BD 02                     STM     2
0021: B6 01 03                  LOD     1, 3
0024: A5 03                     LAO     3
0026: BC 02                     LDM     2
0028: 00                        SLDC    0
0029: 00                        SLDC    0
002A: CF 02                     CGP     2
002C: 9E 00                     CSP     IOCHECK
002E: B6 01 03                  LOD     1, 3
0031: CD 00 16                  CXP     0, 22           ; fwriteln
0034: 9E 00                     CSP     IOCHECK
0036: C1 00             p1_1:   RBP     0
; Procedure 1 Attribute Table:
0038: 04 00                     .word   4               ; data size
003A: 04 00                     .word   4               ; param size
003C: 06 00                     .word   $ - p1_1        ; exit ic
003E: 3E 00                     .word   $ - p1_0        ; enter ic
0040: 01                p1_at:  .byte   1               ; procedure number
0041: 00                        .byte   0               ; lex level

The FLT at 001e converts the integer constant zero to floating point.  That's probably where your testcase is blowing up.  You can use ucsdpsys_disassem to see what your compiler is generating there.

**Comment by ghaerr** [comment] 2021-11-11 23:32
> The II.0 interpreters written at UCSD implemented basic floating point ops directly, called by specific p-opcodes.

Interesting, thanks for that information. Does that mean the interpreter needed to handle them as "UCSD-specific" REALs, possibly implemented in a UC-compatible floating point library specific to the interpreter platform, or were these handed off to hardware if the machine had hardware floating point, and kept and manipulated in that format?

> The FLT at 001e converts the integer constant zero to floating point. That's probably where your testcase is blowing up. 

I see. So these instructions are "converted" by the interpreter to "native" procedure calls? I guess I don't yet understand how the native function call mechanism works in the p-system; I had thought everything was called as a local, intermediate, global, external, or special procedure (with the exception of special opcodes possibly invented afterwards).

Thank you!

**Comment by jdykstra** [comment] 2021-11-12 00:42
> Does that mean the interpreter needed to handle them as "UCSD-specific" REALs, possibly implemented in a UC-compatible 
> floating point library specific to the interpreter platform, or were these handed off to hardware if the machine had hardware
> floating point, and kept and manipulated in that format?

UCSD Pascal specified that floats were two (16-bit) words long, but left their formats implementation-specific.  The x86/Z80 interpreter implemented all of the floating point arithmetic (including transcendental functions) directly on the CPU;  you couldn't count on machines having separate FP processors in the late 1970's.

The PDP-11 interpreter used a different floating point format.  Clearly moving floating point data files between architectures was problematic, but byte sex issues were even more of a problem.  Being able to run the same CODE files on multiple architectures was revolutionary at the time, but the portability wasn't perfect.

> So these instructions are "converted" by the interpreter to "native" procedure calls? I guess I don't yet understand how the 
> native function call mechanism works in the p-system; I had thought everything was called as a local, intermediate, global, 
> external, or special procedure (with the exception of special opcodes possibly invented afterwards).

The floating point opcodes were implemented directly by the interpreter, just the same way all other opcodes were implemented.  That implementation frequently used common functions, but those functions were called via the usual assembly code calling sequences, not via the P-machine function calling mechanism.  It was also possible to call native code via the P-machine mechanism, but that was more an "escape hatch" to implement hardware-specific stuff than a fundamental part of the P-system.  I'm not familiar with the Apple implementation, but I suspect that FP was implemented through a UNIT there for expediency (which is still causing confusion in 2021).

**Comment by ghaerr** [comment] 2021-11-12 19:44
Hello @jdykstra,

Thanks for the explanations of floats and their opcodes, this is helping me to understand how various internal/external bindings take place in the differing implementations and versions of UCSD Pascal.

>  I'm not familiar with the Apple implementation, but I suspect that FP was implemented through a UNIT there for expediency (which is still causing confusion in 2021).

So if a UNIT were used for the Apple implementation (instead of FLT opcodes), then a normal CXP (call external procedure) would be used to call p-code in that unit, correct? And then in the UNIT code itself, there would be some 6502 native code bound in somehow, which would use some sort of p-system "call native" instruction to start executing that? Thus what @lurk101 is seeing with the intrepreter unimplemented instruction halt is a case where a matching signature of native 6502 code was not found, and the interpreter (and interpreter writer) now knowing what code to substitute, correct?

Looking through the UC I.5 and II.0 source code I've been able to find, I only see the LSI-11 and Z80 interpreters, and no special UNIT-style code except LONG_INTEGER. I'm not sure whether those interpreters had a "call native" instruction.

Thanks for bearing with me; just trying to figure out is likely going on.

Thank you!

**Comment by jdykstra** [comment] 2021-11-12 21:41
Native/assembly code support was added sometime before II.0.  There's no special "call native code" opcode;  instead procedures and functions are marked as native code in their jump tables.  In the II.0 User Manual, see Section 3.3.2 for how such procedures are called from Pascal, and in the II.0 Z80 interpeter file PROC1.TEXT, subroutine BLDXNL for how this is implemented.

**Comment by lurk101** [comment] 2021-11-13 00:23
All very enlightening. I have all the tools including cross compiler, but only used mkfs to create a work volume. The port was of the VM only.

From what I can infer the 2 volumes provided are NOT Apple disks. I suspect the issue will also apply to transcendental functions as the same technique is used. REALs and trig functions are an imperative and ideally the compiler would be updated to issue the proper instructions. However I don't know of any version 2.0 Pascal source code for the compiler to update and cross compile. There would be no issue handling floats and transcendental functions directly in the VM on a modern machine.

**Comment by lurk101** [comment] 2021-11-13 06:32
In the disassembled code above the error occurs here.

0028: 00 SLDC 0
0029: 00 SLDC 0
002A: CF 02 CGP 2 <======
002C: 9E 00 CSP IOCHECK
002E: B6 01 03 LOD 1, 3
0031: CD 00 16 CXP 0, 22 ; fwriteln

Now that I have the compiler from https://github.com/jdykstra/ucsd-psystem-os.git cross compiled and running in the VM, I need to figure out where that sequence is generated. The objective is to get rid of the Apple II hack.

**Comment by lurk101** [comment] 2021-11-13 07:56
Ok, this might be doable!

Looking at disassembly of code generated by the cross compiler and the code generated by the cross compiled compiler source.

For

writeln(1.3);

The cross compiler generates:

```
0020: B3 02 A6 3F 66            LDC     2, 16294, 26214 ; 1.3
      66
0026: 00                        SLDC    0
0027: 00                        SLDC    0
0028: CD 1F 04                  CXP     31, 4           ; fwritereal (PASCALIO)
002B: 9E 00                     CSP     IOCHECK
```
But the cross compiled compiler running in the VM produces:

```
001E: B3 02 A6 3F 66            LDC     2, 16294, 26214 ; 1.3
      66
0024: 00                        SLDC    0
0025: 00                        SLDC    0
0026: CF 02                     CGP     2
0028: 9E 00                     CSP     IOCHECK
002A: B6 01 03                  LOD     1, 3
002D: CD 00 16                  CXP     0, 22           ; fwriteln
0030: 9E 00                     CSP     IOCHECK
```
The apple compiler uses CGP 2 instead of the standard CXP 31,4 call.

**Comment by jdykstra** [comment] 2021-11-13 21:39
The components of the P-System contained in my ucsd-psystem-os repro have never passed their build tests, due to a variety of errors which I haven't had the time to track down.  That is why I label that repo as a personal fork rather than as something maintained for use by others.  I do not actively support it.  If you want to build something with it, I'd strongly recommend fixing the problems revealed by the build tests (and submitting pull requests) before throwing any other code at it.

If your focus is building and running Pascal code rather than hacking on the tools, I recommend using the compiler on Peter's system disk image, running on the VM.

**Comment by lurk101** [comment] 2021-11-14 09:10
Understood. Would you accept pull request?

For example. The real variables are far better supported than I expected. The crashing pieces are only the real input and output hacks.

By making a little room in main for a formatting buffer in main

`
    Np = HEAP_BOT + 0x10; // make space  for real formatting buffer
    Kp = KP_TOP;
    Kp = WordIndexed(Kp, -SYSCOM_SIZE);
    Syscom = Kp;
`
and patching the CGP instruction, writeln works for reals and operators are functional.
`        case CGP:
            p1 = FetchUB();
            if (p1 == 2) {
                word D = Pop();
                word W = Pop();
                float X = PopReal();
                word F = Pop();
                word F2 = Pop();
                word s[16];
                char f[16];
                if ((D == 0) && (W == 0))
                    strcpy(f, "%f");
                else if (D == 0)
                    sprintf(f, "%%%df", W);
                else
                    sprintf(f, "%%%d.%df", W, D);
                int lb = sprintf((char*)s + 1, f, X);
                *((char*)s) = lb;
                for (int l = 0; l < (lb + 1) / 2; l++) // Use syscom extensions 4-8
                    MemWr(HEAP_BOT + l, s[l]);
                Push(F2);
                Push(F);
                Push(HEAP_BOT);
                Push(W);
                // cxp 0,19
                word w = SegDict[0].Seg;
                if (call(w, 19, StaticLink(w, 19)))
                    CspUnloadSegment(p1);
                break;
            }
            call(Seg, p1, Base);
            break;
`
Next, readln for reals.

**Comment by jdykstra** [comment] 2021-11-14 21:42
I don’t understand what you’re trying to do, and why you can’t compile your Pascal code as I suggested in my previous comment.  Do you have a CODE file compiled for Apple Pascal for which you don’t have the source?

FWIW, FWRITEREAL() is present (written in Pascal) in P-System version 1.5 and later.  There shouldn’t be any need to re-implement it in C in the VM.

See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests for how to create a pull request.  However, let’s talk about your problem first, to make sure we’re aligned on how to fix your problem.

**Comment by jdykstra** [comment] 2021-11-14 21:42
I don’t understand what you’re trying to do, and why you can’t compile your Pascal code as I suggested in my previous comment.  Do you have a CODE file compiled for Apple Pascal for which you don’t have the source?

FWIW, FWRITEREAL() is present (written in Pascal) in P-System version 1.5 and later.  There shouldn’t be any need to re-implement it in C in the VM.

See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests <https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests> for how to create a pull request.  However, let’s talk about your problem first, to make sure we’re aligned on how to fix your problem.

  —  John

**Comment by jean-m-cyr** [comment] 2021-11-15 02:14
I'm not trying to run any program in particular. I'm trying to create a robust UCSD P System that will run stand alone on the Raspberry Pico, a tiny SBC without OS.

You're absolutely right, they exist in PASCALIO but the current VM assumes that any external functions residing in segments other than zero are native code, hence the call to native6502.c. FWRITEREAL and FREADREAL are part of segment 31, as you say PCode, definitely NOT native code!

That explains my initial attempt to implement natively. I've since bound the Pascal functions correctly in my port and they now work as intended! I'm guessing that these functions were implemented natively in the Apple II.

Anyhow, thanks for the help.

**Comment by jdykstra** [comment] 2021-11-15 02:23
Thanks for the update, and I'm glad that you've resolved the problem.  If you're discovered any portability problems in moving the VM to ARM, I'd love to see them opened as issues on GitHub.  Thanks!

**Closed as completed by jdykstra** 2021-11-15 02:23 UTC
